### ISSUE TITLE
Animation of network

### ISSUE THREAD

**Issue by yinghaodai** [vandenheuvel/tribler#10]
Animating the network display could help the user get a better understanding of it. Possible applications:
- Highlight where clusters are
- Highlight where possible leechers are
- Show how relationships between nodes have changed over time
- Show how reputations of nodes have changed and possibly what caused this effect

**Comment by synctext** [comment]
![animation1](https://cloud.githubusercontent.com/assets/325224/25713204/3bf7a762-30f4-11e7-9938-9dff58623a8c.gif)

![image](https://cloud.githubusercontent.com/assets/325224/25713202/37ebfb8c-30f4-11e7-9a0f-297f54f3a0c2.gif)
