### ISSUE TITLE
[2] The trust display should be "pre-loaded" to avoid the white flash when starting the QWebEngine

### ISSUE THREAD

**Issue by vandenheuvel** [vandenheuvel/tribler#157]
When opening the trust display for the first time after opening Tribler, the QWebEngine loads the web page. For a short while, before the page is loaded, a white screen is shown. We want to avoid this.

**Comment by rkeulemans** [comment]
@vandenheuvel As the other team members don't seem to have this issue can you indicate a way to how to reproduce this? Do you have any idea what the problem is?

**Comment by vandenheuvel** [comment]
@rkeulemans this was reproduced just yesterday at @MaxVanDeursen's device.
