### ISSUE TITLE
[20] Show detailed information when hovering over nodes and links

### ISSUE THREAD

**Issue by rkeulemans** [vandenheuvel/tribler#171]
As a user:

- [x] when I hover over a node I would like to see: the page rank score, total amount of transmitted data, public key. 
- [x] when I hover over a edge I would like to see: amount of data uploaded and downloaded, in a reasonable unit (i.e. kB/MB/GB when appropriate).

**Comment by ghabbenjansen** [comment]
Implemented in PR #173
