### ISSUE TITLE
[5] Fix an unstable multichain database test

### ISSUE THREAD

**Issue by vandenheuvel** [vandenheuvel/tribler#191]
`TestDatabase.test_neighbors` isn't entirely stable. If fails sometimes, see for example [this build](https://jenkins.tribler.org/job/pers/job/vandenheuvel/job/GH_Tribler_vandenheuvel_PR_tests_linux/321/).

**Comment by ghabbenjansen** [comment]
This was fixed in PR #196 
(Also described in issue #197)
