### ISSUE TITLE
[40] Naive iterative pagerank implementation

### ISSUE THREAD

**Issue by MaxVanDeursen** [vandenheuvel/tribler#23]
As a developer, it is possible to iteratively calculate pagerank on a graph. That is:

- [x] I can use an initial graph as input for the calculation
- [x] I can update the calculation for a new node
- [x] I can update the calculation for a new edge
- [x] I can output the results
- [x] Integrated into the Tribler code

Performance is not yet a priority, no optimizations have to be performed.

**Comment by TimSpeelman** [comment]
Dit is toch geen ready story?

**Comment by vandenheuvel** [comment]
You're right, this is a feature. Thanks.
