### ISSUE TITLE
[3] Doing the necessary processing of trust-statistics in the GUI

### ISSUE THREAD

**Issue by vandenheuvel** [vandenheuvel/tribler#44]
As a developer, I want to be able to process the data from the HTTP endpoint to be used in the visualization so that the visualization works with the HTTP API

Some results probably have to be prepared in the GUI, but we should keep this to a minimum.

- [x] Agreeing on a clear interface
- [ ] Implementing these methods

**Comment by rkeulemans** [comment]
Data formats:
- Note: this applies relative to the focus node (your own node) first.
- Array with tuples (upload, download) ordered on the sum upload + download from high [0] to low [n].
- Array with ratio upload / (upload + download), so the index from the above array can be used.
