### ISSUE TITLE
Filtering the data in the visualization on a specific time frame.

### ISSUE THREAD

**Issue by TimSpeelman** [vandenheuvel/tribler#53]
As a user, I want to be able to see how much data two nodes have exchanged up until a certain point in time, so I can see the evolution of the network.

- [ ] Add a date input field to the Trust Display window
- [ ] Update the graph data when the date input field changes
- [ ] Clearly indicate whether the data is current, or limited to a specified date

- [ ] #124

**Comment by vandenheuvel** [comment]
We won't pursue this any further, see #124.
